### ISSUE TITLE
sudo

### ISSUE THREAD

**Issue by Ethal** [lunarok/jeedom_nodejs#1]
Bonsoir,
juste une remarque , faudrait vérifier que le user "sudo" existe 
un truc du genre whoami pourrait aider ou :

```
if sudo -n true 2>/dev/null; then 
    echo "I got sudo"
else
    echo "I don't have sudo"
fi
```

**Comment by lunarok** [comment]
Le script d'installation de jeedom installe sudo, le kamikaze qui fait du jeedom sans est pas sortit de l'auberge :)
https://github.com/jeedom/core/blob/1751e6a052cea8f443e0610563d5b305a4f229f6/install/install.sh#L47

**Comment by Ethal** [comment]
Exact, bien vu
